### ISSUE TITLE
Allow dynamic server name and port number

### ISSUE THREAD

**Issue by nicolas-heigvd** [baremaps/openstreetmap-vecto#14]
Setting server parameters in config.yaml doesn't seem to be 100% effetive:

E.g. by changing:
```
server:
  host: localhost
  port: 9000
```
which gives `HTTP/1.1 200 OK`

to:

```
server:
  host: localhost
  port: 9500
```

an re-launching `./start.sh`, the new port seems to be taken into account:

```
[INFO ] 2021-02-18 18:24:46.051 [armeria-boss-http-*:9500] Server - Serving HTTP at /0.0.0.0:9500 - http://127.0.0.1:9500/
```

But the website is no more responding:
```
$ http localhost:9500

http: error: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) while doing GET request to URL: http://localhost:9500/
```

In addition, if we change the host name, it doesn't affect the server:

in `config.yaml`:
```
server:
  host: some.server.org
  port: 9500
```
gives this after restarting the server:    
```
[INFO ] 2021-02-18 18:24:46.051 [armeria-boss-http-*:9500] Server - Serving HTTP at /0.0.0.0:9500 - http://127.0.0.1:9500/
``` 
and the site is still unreachable:
```
$ http some.server.org:9500

http: error: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) while doing GET request to URL: http://some.server.org:9500/
```

Therefore, one should allow both the host name and port to be set up dynamically, e.g. using env variables.    
For the moment, they seem hard-coded: https://github.com/baremaps/baremaps/blob/f13815324b22f287e5761bb1376184022544e373/baremaps-config/src/main/java/com/baremaps/config/Server.java#L19-L21

**Comment by bchapuis** [comment]
The [hard-coded values](https://github.com/baremaps/baremaps/blob/f13815324b22f287e5761bb1376184022544e373/baremaps-config/src/main/java/com/baremaps/config/Server.java#L19-L21) are default values used when the configuration file does not specify them. 

If you want the domain name `some.server.org` to work locally, you should probably add the following line to your `/etc/hosts` file, to prevent it from being resolved with DNS. `some.server.org` exists and has an IP address.

```
0.0.0.0 some.server.org
```

Have you tried to do something like

```
http 0.0.0.0:9500
```

**Comment by nicolas-heigvd** [comment]
It sounds like I misunderstood that the port specified in the `config.yaml` is the one used by the app _inside_ the docker container, it is not the one published on the host, which I think it actually was. You won't be actually able to notice this if you use the same port number when mapping them (e.g. using `--publish 9000:9000`) during the container startup.

So, I let it match the given docker port in the `config.yaml` file. And everything works fine locally, both when reaching localhost:HOST_PORT _and_ some.server.org 

But then I face the CORS issues when I reach the site from another machine, for which I'll open a new issue even so it's probably related in some way.
