### ISSUE TITLE
Flatten trees on the map plane when viewed with some inclination angle on the canvas

### ISSUE THREAD

**Issue by nicolas-heigvd** [baremaps/openstreetmap-vecto#18]
It is quite funny to see that trees are actually not represented on the map plane when viewed with some inclination angle:

![image](https://user-images.githubusercontent.com/35065252/108563424-b85a0180-7301-11eb-8292-b2a32e344f29.png)

May this simply be corrected so that they are flattened on the map plane and represented as ellipses?

**Comment by bchapuis** [comment]
The `circle-pitch-alignment` property can probably be used to fix this issue.

https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-pitch-alignment

https://github.com/mapbox/mapbox-gl-js/issues/4120
