### ISSUE TITLE
Add { "text-optional" : true } and { "allow-overlap" : false } to all poi

### ISSUE THREAD

**Issue by Yahia1018** [baremaps/openstreetmap-vecto#198]
I purpose to add { "text-optional" : true } to all poi, in order to avoid to have too much text displayed on the window, as in OpenStreetMap.

**Comment by bchapuis** [comment]
Shouldn't we set priorities? E.g. mandatory for city names, optional for shop names.

**Comment by bchapuis** [comment]
That being said, it is not easy to keep track of all these rules as they are scattered in the stylesheet. We may need to have a document that summarizes and document our choices. What do you think?

**Comment by Yahia1018** [comment]
Yes, the document is a good idea! It will be easier to decide.

About the priorities, I think there are already present with the choices of the order of the layers. But if you are agree we could try to take off the _allow-overlap_ property of the poi. That will change from that : 

<img width="250" alt="Capture d’écran 2022-02-11 à 15 20 42" src="https://user-images.githubusercontent.com/91720525/153608707-5a801ae1-c42c-4a45-a951-eb18db1ac2b8.png">

To that when we change the zoom level : 

<img width="250" alt="Capture d’écran 2022-02-11 à 15 20 01" src="https://user-images.githubusercontent.com/91720525/153608752-b12b9519-c851-4231-ab8a-f3221106eee9.png"> <img width="257" alt="Capture d’écran 2022-02-11 à 15 20 23" src="https://user-images.githubusercontent.com/91720525/153608760-66028d7e-858c-4aff-bb3a-0caaddccea30.png">
