### ISSUE TITLE
EHN: remove prune -a from the README

### ISSUE THREAD

**Issue by nicolas-heigvd** [baremaps/openstreetmap-vecto#20]
@MarBesse Can you please, when you have some free time, review the Windows Troubleshooting section of the [README](https://github.com/baremaps/openstreetmap-vecto/blob/main/README.md#troubleshooting-windows) to avoid the use of [`docker system prune -a`](https://docs.docker.com/engine/reference/commandline/system_prune/). The `-a` flag _may_ be especially dangerous if you host multiple applications on the same machine and some are down for whatever reason.    

Prefer removing a specific container using [`docker rm <container>`](https://docs.docker.com/engine/reference/commandline/rm/) and a specific image using [`docker rmi <image>`](https://docs.docker.com/engine/reference/commandline/rmi/) (in that latter case, no container using the image you want to remove must be running).

You can even clean your docker unused objects (which indeed is sometimes a good practice) using [`docker system prune`](https://docs.docker.com/config/pruning/) or even `docker system prune -v` but keep in mind that the `-v` (similar to `--volumes`)  flag is intended to remove [volumes managed by docker](https://docs.docker.com/storage/), which are often used to store media files or databases, so if you remove them, you _will_ have to re-create new volumes next time you spin up your application, which can cost some time, especially when large database have to be build.

;-)

**Comment by bchapuis** [comment]
I'm guilty one behind this commit, but I agree we shouldn't add this kind of dangerous commands in our documentation.
