### ISSUE TITLE
Add landuse_industrial labels

### ISSUE THREAD

**Issue by Yahia1018** [baremaps/openstreetmap-vecto#212]
I don't understand why there is a duplicate purple zone. One with the tag `power = plant` :

<img width="300" alt="building_industrial-labels-2" src="https://user-images.githubusercontent.com/91720525/154079520-fc29e127-7358-4de0-914b-30055537e5ac.png">

Here (hiding the `power = plant`) with the tag `landuse = industrial` :

<img width="300" alt="building_industrial-labels-OSM" src="https://user-images.githubusercontent.com/91720525/154079515-31fdb7b3-4764-49ee-b43d-1327b57d31c0.png"> <img width="307" alt="building_industrial-labels-1" src="https://user-images.githubusercontent.com/91720525/154079529-0c94184d-002d-43a0-a98e-516e4aa7ae6b.png">

Do we need the `power = plant` one @bchapuis ? Or I can maybe replace the tag in _power_station_ layer by a `[ "all", [ "==", "power", "plant" ], [ "!has", "landuse" ] ]` to be sure ?

**Comment by bchapuis** [comment]
I think the styling rule should based on the landuse property.
https://wiki.openstreetmap.org/wiki/Tag:landuse=industrial

**Comment by bchapuis** [comment]
Actually, I'm not sure...
https://wiki.openstreetmap.org/wiki/File:Mapnik-power.png
https://wiki.openstreetmap.org/wiki/Tag:power=plant

**Comment by bchapuis** [comment]
I looks like openstreetmap-carto has two distinct rules.

One for industrial:
https://github.com/gravitystorm/openstreetmap-carto/blob/1178dfba278f1eee0ce018f72bcc88b5596d2929/style/landcover.mss#L22

And one for power (based on industrial):
https://github.com/gravitystorm/openstreetmap-carto/blob/1178dfba278f1eee0ce018f72bcc88b5596d2929/style/landcover.mss#L51

**Comment by Yahia1018** [comment]
Ok thanks for the informations, I'll work on it.
