### ISSUE TITLE
Set environment variable in config.yaml

### ISSUE THREAD

**Issue by nicolas-heigvd** [baremaps/openstreetmap-vecto#24]
As an integrator,

I want to be able to pass environment variables defining the server name and the port in the `config.yaml` file:
```
server:
  host: ${BAREMAPS_SITES_DOMAIN}
  port: ${DB_APP_PORT}
```

in order to dynamically setup the environment in the front-end.

If I do so, it currently raises:    
```
[ERROR] 2021-02-25 23:58:56.543 [main] Preview - Unable to read the configuration file.
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "${DB_APP_PORT}": not a valid `int` value
 at [Source: (byte[])"id: OpenStreetMapVecto
server:
  host: ${BAREMAPS_SITES_DOMAIN}
  port: ${DB_APP_PORT}
```

And `DB_APP_PORT` does actually exist in the current shell:    
```
# echo ${DB_APP_PORT}
9000
```

From the error message, it may "just" be a simple `string` to `int` conversion to implement somewhere. I hope so. 

\# Follow up of https://github.com/baremaps/openstreetmap-vecto/issues/14

**Comment by bchapuis** [comment]
Yes, this is a good idea. I'm not sure about how to implement this in baremaps with the Jackson parser, but I will investigate it.
