### ISSUE TITLE
Add openapi stuff

### ISSUE THREAD

**Issue by b4l** [baremaps/openstreetmap-vecto#33]
I would be convenient to add some openapi setup stuff here as well. Unfortunately i have no permissions to create a pr.

**Comment by bchapuis** [comment]
I granted you access to the repo. Could you elaborate more on what you plan to add?

**Comment by b4l** [comment]
Thanks! Basically what is in the linked pr for now.

It would also be nice to start the openapi BaremapsServer from the command line. I thinks Andrea is working on this but busy at the moment.
