### ISSUE TITLE
Reorder layers

### ISSUE THREAD

**Issue by Yahia1018** [baremaps/openstreetmap-vecto#50]
We will reorder layers as far as possible, e.g. we have for example to pay attention to not put the buildings above the buildings numbers :

<img width="200" alt="Capture d’écran 2021-12-17 à 16 13 03" src="https://user-images.githubusercontent.com/91720525/146565922-39a04f26-b8c2-4b22-8d62-22761b86dd67.png">

The goal here is to group them by the beginning of their ids (for example building_...) in order to condense the layers side bar in Maputnik.

<img width="175" alt="Capture d’écran 2021-12-17 à 16 15 47" src="https://user-images.githubusercontent.com/91720525/146566233-78c1344c-b5b6-4a7c-a6b5-cdc192e83101.png"> <img width="175" alt="Capture d’écran 2021-12-17 à 16 15 55" src="https://user-images.githubusercontent.com/91720525/146566257-cb7a2d79-b39b-4faa-9d21-429616344a6a.png">

**Comment by Yahia1018** [comment]
I noticed that the layer "aerialway" should be above the "highway_path" and "landuse_forest" layers and certainly above the other highway and landuse layers. We can see that in OpenStreetMap and after doing that modification in Baremaps here :

<img width="250" alt="Capture d’écran 2021-12-20 à 13 10 42" src="https://user-images.githubusercontent.com/91720525/146769262-29608182-5017-48f0-9e0a-6dc90f65ca53.png"> <img width="250" alt="Capture d’écran 2021-12-20 à 13 10 31" src="https://user-images.githubusercontent.com/91720525/146769403-4f5c027f-c99b-4e3d-a84f-16be73861772.png">

(There is another thing to do if we want to correctly display the aerialway, but we will do that in another issue.)

**Comment by Yahia1018** [comment]
This issue made me realize that the goal here was not only to reorder the side bar but also to correct some relative positions between different layers and reorganize the display all of that.

I made many changes, it will certainly be unreadable in the style.json because when I wanted to change the place of one layer in Maputnik, it was announced as a deletion and an addition at the new place, I am sorry about that. I will justify my modifications in order to make the file more pleasant to consult.

**Comment by Yahia1018** [comment]
#### aerialway - power_cable_line

Here we see that _aerialway_ layer must be above _power_cable_line_ layer : 

<img width="250" alt="aerialway-power_cable_line-OSM" src="https://user-images.githubusercontent.com/91720525/146928294-a7d52440-d076-476f-82da-124c735545a9.png"> <img width="250" alt="aerialway-power_cable_line" src="https://user-images.githubusercontent.com/91720525/146928313-835555c1-496a-497f-bf35-511a5bba214f.png">

(I will always put OpenStreetMap at the left and Baremaps at the right.)

**Comment by Yahia1018** [comment]
#### amenity_education - leisure_pitch

Here we see that _leisure_pitch_ layer must be above _amenity_education_ layer : 

<img width="250" alt="amenity_education-leisure_pitch-OSM" src="https://user-images.githubusercontent.com/91720525/146929015-30e4bece-4988-4870-9432-a4332778cd02.png"> <img width="250" alt="amenity_education-leisure_pitch" src="https://user-images.githubusercontent.com/91720525/146929552-35b82593-ec07-4a08-a699-cebf4e089642.png">

**Comment by Yahia1018** [comment]
#### amenity_fountain - leisure_park

Here we see that _amenity_fountain_ layer must be above _leisure_park_ layer : 

<img width="250" alt="amenity_fountain-leisure_park-OSM" src="https://user-images.githubusercontent.com/91720525/146930187-c5905d0b-2b45-4e13-868d-2cb8845cc3ce.png"> <img width="225" alt="amenity_fountain-leisure_park" src="https://user-images.githubusercontent.com/91720525/146930219-8ef0f4d7-ac76-4675-a62b-56018e586d2e.png">

**Comment by Yahia1018** [comment]
#### boundary - power_cable_line - aerialway

Here we see not easily that _boundary_ layer must be under _power_cable_line_ and _aerialway_ (on the right) layers : 

<img width="300" alt="boundary-power_cable_line-aerialway-OSM" src="https://user-images.githubusercontent.com/91720525/146930666-3e6e0358-f238-4ab1-800f-64f2bc81faea.png"> <img width="300" alt="boundary-power_cable_line-aerialway" src="https://user-images.githubusercontent.com/91720525/146931529-d8c87af5-84f1-47bf-841a-bb8d86d3a05d.png">

**Comment by Yahia1018** [comment]
#### building - leisure_swimming_pool

Here we see that _building_ layer must be above _leisure_swimming_pool_ layer (it was already the case) : 

<img width="250" alt="building-leisure_swimming_pool-OSM" src="https://user-images.githubusercontent.com/91720525/146931814-eee17a8c-378c-4078-8068-5e4a30446c76.png"> <img width="250" alt="building-leisure_swimming_pool" src="https://user-images.githubusercontent.com/91720525/146934164-dd5dbf04-9639-44ca-ad4e-1a03afdf800c.png">

**Comment by Yahia1018** [comment]
#### leisure_marina - water

Here we clearly see that _leisure_marina_ layer must be under _water_ layer (it was already the case) : 

<img width="250" alt="leisure_marina-water-OSM" src="https://user-images.githubusercontent.com/91720525/146934414-2058d952-bf97-4f6c-bfbc-3870cdfba436.png"> <img width="250" alt="leisure_marina-water" src="https://user-images.githubusercontent.com/91720525/146934448-11dd0773-673e-4e62-a261-cf39aca92ba1.png">

(On the right image, I show when it is not like mentionned.)

**Comment by Yahia1018** [comment]
#### man_made_pier - leisure_marina - boundary

Here we see that _boundary_ layer must be above _man_made_pier_ and _leisure_marina_ layers (it was already the case) : 

<img width="300" alt="man_made_pier-leisure_marina-boundary-OSM" src="https://user-images.githubusercontent.com/91720525/146935249-ebe6d5f4-e73b-4324-9d03-d9b1c4f8d215.png"> <img width="250" alt="man_made_pier-leisure_marina-boundary" src="https://user-images.githubusercontent.com/91720525/146935268-b0639a87-72cd-4c09-864f-391b7f7b2cb8.png">

**Comment by Yahia1018** [comment]
#### man_made_pier - natural_tree

Here we see that _man_made_pier_ layer must be under _natural_tree_ layer : 

<img width="275" alt="man_made_pier-natural_tree-OSM" src="https://user-images.githubusercontent.com/91720525/146935565-6dd69770-2b8a-4f98-9e1e-6f1f03fc08d0.png"> <img width="250" alt="man_made_pier-natural_tree" src="https://user-images.githubusercontent.com/91720525/146935579-a1dbe40c-98c9-430c-beeb-cede78a0668c.png">

(I show here to the right the error before modification, in order to understand the goal of it.)

**Comment by Yahia1018** [comment]
#### natural_tree - power_cable_line

Here I think that _natural_tree_ layer should be above _power_cable_line_ layer and should be a little transparent : 

<img width="250" alt="natural_tree-power_cable_line-OSM" src="https://user-images.githubusercontent.com/91720525/146936754-83b676a5-9446-46e5-adfd-b9fa760b4648.png"> <img width="275" alt="natural_tree-power_cable_line" src="https://user-images.githubusercontent.com/91720525/146936761-9ffe91be-e2e5-4c5d-8684-418619b47f76.png">

**Comment by Yahia1018** [comment]
#### railway_light_rail - highway_path - natural_tree - natural_trunk

Here, same as the last comment, I think that _natural_tree_ and _natural_trunk_ layers should be above _railway_light_rail_ layer and in fact above all _highway_ layers (we don't see that here, I could show it if you want).

We can also see that _railway_light_rail_ layer must be above _highway_path_ layer : 

<img width="300" alt="railway_light_rail-highway_path-natural_tree_trunk-OSM" src="https://user-images.githubusercontent.com/91720525/146941234-b6591af2-3702-4580-a3a0-df8ba34b7c8c.png"> <img width="300" alt="railway_light_rail-highway_path-natural_tree_trunk" src="https://user-images.githubusercontent.com/91720525/146941257-e806d90f-9bcb-448a-b280-962148e092cf.png">

**Comment by Yahia1018** [comment]
#### railway_rail - railway_rail_offset \ highway_primary - highway_primary_casing

We see here that _railway_rail_ and _railway_rail_offset_ layers must be under _highway_primary_ and _highway_primary_casing_ layers : 

<img width="275" alt="railway-highway-OSM" src="https://user-images.githubusercontent.com/91720525/146946494-57d34c72-bf88-42ab-ae85-b7b34a71759c.png"> <img width="300" alt="railway-highway" src="https://user-images.githubusercontent.com/91720525/146946514-93cac354-11c8-45b1-84b9-04a59f87adf6.png">

I realized with that comment that I made an error, I forgot to put _railway_ layers above _highway_path_ layer. After this realization I also think that all _highway_ layers that are not for vehicles should be under the _railway_ layers, I will verify that.

**Comment by bchapuis** [comment]
I think it is good to have concrete examples for the ordering problem. Indeed, we will have to split some groups in order to display the layers correctly.

**Comment by Yahia1018** [comment]
I think I didn't understand what you were meaning by "concrete examples", but after a long period of difficulties in order to reajust these layers I think I understand now that you said we should better look at a little piece of Map like we did, and at this moment correct the order of layers, step by step. Was that what you wanted to advise me ?

**Comment by bchapuis** [comment]
I was referring to the screenshots. The structure of the style should be as easy to understand as possible (e.g. by grouping layers), but not to the detriment of the result.
