### ISSUE TITLE
Forests are hidden by leisure areas

### ISSUE THREAD

**Issue by bchapuis** [baremaps/openstreetmap-vecto#54]
![Screenshot 2022-01-04 at 10 15 32](https://user-images.githubusercontent.com/238747/148036650-fd195ca8-f9fb-4aec-90d6-78dd9ddf7cd6.png)
![Screenshot 2022-01-04 at 10 15 42](https://user-images.githubusercontent.com/238747/148036660-624facb3-040a-4e60-8282-f54ec8a35c76.png)

**Comment by Yahia1018** [comment]
I don't know why but there are five _ "layout" -> "visibility" -> "visible" _ left to remove, I'm sure there weren't any when I pushed the commit to #55. Sorry. Can I do it in this issue, or do you prefer another way?

**Comment by Yahia1018** [comment]
I decided to create the _natural_wood_ layer (extracted from the _natural_ layer match expression) and to place it above the _landuse_, _amenity_ and _leisure_ layers. We can strongly think that the woods must be above these three types of layers. 

For the _landuse_ layer, I have a little proof here :

<img width="450" alt="natural_wood-landuse-OSM" src="https://user-images.githubusercontent.com/91720525/148052916-729270eb-8811-46e1-a40f-816b56236e10.png"> <img width="450" alt="natural_wood-landuse" src="https://user-images.githubusercontent.com/91720525/148052970-495a35ec-0473-4ce0-8cfa-fcd8ae4a1cdc.png">

**Comment by bchapuis** [comment]
> I don't know why but there are five _ "layout" -> "visibility" -> "visible" _ left to remove, I'm sure there weren't any when I pushed the commit to #55. Sorry. Can I do it in this issue, or do you prefer another way?

Sure, no problem.

**Comment by bchapuis** [comment]
> I decided to create the _natural_wood_ layer (extracted from the _natural_ layer match expression) and to place it above the _landuse_, _amenity_ and _leisure_ layers. We can strongly think that the woods must be above these three types of layers.

Sounds good to me.
