### ISSUE TITLE
Highway_service on natural_wood instead of next to

### ISSUE THREAD

**Issue by Yahia1018** [baremaps/openstreetmap-vecto#57]
There is a little problem here that I don't know how to resolve right now, but I create this issue and I will think about it. _highway_service_ layer must be next to _natural_wood_ layer here, but it is on it : 

<img width="300" alt="highway_service-natural_wood-OSM" src="https://user-images.githubusercontent.com/91720525/148079168-4b641e0c-975e-486a-875e-1b53806aac27.png"> <img width="300" alt="highway_service-natural_wood" src="https://user-images.githubusercontent.com/91720525/148079190-ae8e909f-15c2-4c74-9c6d-55a802fd32fe.png">

**Comment by bchapuis** [comment]
I think the difference is in the data used to produced the map. You cannot solve this at the level of the stylesheet.

**Comment by Yahia1018** [comment]
Oh, I see. So it is something you can solve and we keep the issue open, or is it impossible ?

**Comment by bchapuis** [comment]
It cannot be solved at this level, so I would simply close the issue
