### ISSUE TITLE
Waterway tunnel, railway with "spur" service, private highway_service and railway level_crossing

### ISSUE THREAD

**Issue by Yahia1018** [baremaps/openstreetmap-vecto#58]
Here, we can display the tunnel where the water is flowing, make the difference between short tracks of railway which are normally for freight and long tracks of railway, make the difference between private highway_service and those are not and display the railway level_crossing.

<img width="387" alt="waterway_tunnel-etc-OSM" src="https://user-images.githubusercontent.com/91720525/148094494-0082671f-bf90-4847-baba-271913eca3d4.png"> <img width="350" alt="waterway_tunnel-etc" src="https://user-images.githubusercontent.com/91720525/148095055-2f604319-1a20-4027-a2b3-68545584a419.png">

- [x] Display the waterway_tunnel
- [x] Distinguish short tracks of railway from long
- [x] Distinguish private highway_service from not private
- [ ] Display the railway level_crossing

**Comment by Yahia1018** [comment]
About the edit : 

<img width="200" alt="spur-service" src="https://user-images.githubusercontent.com/91720525/148223928-8f6313bd-af5b-4e4a-b5d5-1eee369ae2c8.png">

**Comment by Yahia1018** [comment]
@bchapuis I tried for a long moment to display the icon of the railway level_crossing, but I didn't success. Can you help me please ?

**Comment by bchapuis** [comment]
@Yahia1018 I guess that level_crossing should be displayed with icons. As we don't have a good set of icons in the style yet, we should probably create a separate issue for this.
