### ISSUE TITLE
Do we really need to mount a volume from the current dir when it has already been copied by the Dockerfile?

### ISSUE THREAD

**Issue by nicolas-heigvd** [baremaps/openstreetmap-vecto#9]
Are there any reasons to mount the local folder at build time https://github.com/baremaps/openstreetmap-vecto/blob/f90808734bae968b8501cb6212cc70fa3ea0a733/Dockerfile#L19 **and** to bind mount the same folder when creating the container https://github.com/baremaps/openstreetmap-vecto/blame/main/README.md#L27 ?

It seems a redundant potpourri between a dev and and prod process to me, but I may have missed something...

**Comment by bchapuis** [comment]
The idea is to let the user edit the configuration on his file system and to automatically reload them in the docker container and in the browser with baremaps. This is redundant, but If you decide to use the image generate the map from a server (not for dev), it is usefull to have a copy of the configuration shipped with it. What do you think?

**Comment by nicolas-heigvd** [comment]
I think it's precisely the reason why I can often see a separate `Dockerfile.dev` which embed some development tools for example, along a `docker-compose.yml` file which actually mounts the current folder. Whereas you copy your application code within a minimalist but self-sufficient `Dockerfile.prod` in production mode, using an `ADD` or `COPY` instruction along with a `.dockerignore` file to not embed fancy stuff (your git history is useless in your Docker image for example). And if you can avoid to have two separate Dockerfiles and use a global switch between dev and prod, it is even better, but you cannot always do that.

\# _Humble docker user._

Further readings:    
https://docs.docker.com/develop/dev-best-practices/    
https://vsupalov.com/same-dockerfile-dev-staging-production/    
https://stackoverflow.com/questions/46440909/how-to-configure-different-dockerfile-for-development-and-production

**Comment by bchapuis** [comment]
Sounds great, thank you for the pointers. It looks like we would benefit from moving away from my current config.
